kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golang
    failure: ignore
    commands:
      - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
      - golangci-lint run

#  - name: test
#    image: golang
#    commands:
#      - go test ./checksum/

  - name: build
    image: golang
    commands:
      - go build

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      title: ${DRONE_TAG} Release
      note: CHANGELOG.md
      api_key:
        from_secret: gitea_token
      base_url: https://git.neveris.one
      files: cbr2cbz
      checksum:
        - sha256
    when:
      event: tag

  - name: github_release
    image: plugins/github-release
    settings:
      title: ${DRONE_TAG} Release
      note: CHANGELOG.md
      api_key:
        from_secret: github_token
      files: cbr2cbz
      checksum:
        - sha256
    when:
      event: tag
